# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalendarFormUFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalendarForm(object):
    def setupUi(self, CalendarForm):
        CalendarForm.setObjectName("CalendarForm")
        CalendarForm.resize(312, 220)
        self.calendarWidget = QtWidgets.QCalendarWidget(CalendarForm)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 312, 183))
        self.calendarWidget.setObjectName("calendarWidget")
        self.OK = QtWidgets.QPushButton(CalendarForm)
        self.OK.setGeometry(QtCore.QRect(250, 190, 51, 23))
        self.OK.setStyleSheet("font-family: Verdana;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"border-radius: 10px;\n"
"color: white;\n"
"")
        self.OK.setObjectName("OK")
        self.date_label = QtWidgets.QLabel(CalendarForm)
        self.date_label.setGeometry(QtCore.QRect(10, 190, 231, 23))
        self.date_label.setStyleSheet("font-family: Verdana;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"border-radius: 10px;\n"
"color:  black;")
        self.date_label.setObjectName("date_label")

        self.retranslateUi(CalendarForm)
        QtCore.QMetaObject.connectSlotsByName(CalendarForm)

    def retranslateUi(self, CalendarForm):
        _translate = QtCore.QCoreApplication.translate
        CalendarForm.setWindowTitle(_translate("CalendarForm", "Календарь"))
        self.OK.setText(_translate("CalendarForm", "ОК"))
        self.date_label.setText(_translate("CalendarForm", "Выбранная дата:"))
