# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createacc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateUser(object):
    def setupUi(self, CreateUser):
        CreateUser.setObjectName("CreateUser")
        CreateUser.resize(381, 156)
        CreateUser.setStyleSheet("")
        self.label = QtWidgets.QLabel(CreateUser)
        self.label.setGeometry(QtCore.QRect(10, 0, 251, 21))
        self.label.setStyleSheet("font-size: 15pt;\n"
"font-family: Verdana, serif;\n"
"color: black;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(CreateUser)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 101, 20))
        self.label_2.setStyleSheet("font-size: 10pt;\n"
"font-family: Verdana, serif;\n"
"color: black;\n"
"font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.login = QtWidgets.QLineEdit(CreateUser)
        self.login.setGeometry(QtCore.QRect(180, 30, 191, 21))
        self.login.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 10pt;")
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(CreateUser)
        self.password.setGeometry(QtCore.QRect(180, 60, 191, 21))
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 10pt;")
        self.password.setText("")
        self.password.setObjectName("password")
        self.label_3 = QtWidgets.QLabel(CreateUser)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.label_3.setStyleSheet("font-size: 10pt;\n"
"font-family: Verdana, serif;\n"
"color: black;\n"
"font-weight: bold;")
        self.label_3.setObjectName("label_3")
        self.sign_up_button = QtWidgets.QPushButton(CreateUser)
        self.sign_up_button.setGeometry(QtCore.QRect(290, 120, 81, 21))
        self.sign_up_button.setStyleSheet("font-family: Verdana;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"border-radius: 10px;\n"
"color: white;")
        self.sign_up_button.setObjectName("sign_up_button")
        self.confirmpass = QtWidgets.QLineEdit(CreateUser)
        self.confirmpass.setGeometry(QtCore.QRect(180, 90, 191, 21))
        self.confirmpass.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 10pt;")
        self.confirmpass.setText("")
        self.confirmpass.setObjectName("confirmpass")
        self.label_4 = QtWidgets.QLabel(CreateUser)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 171, 21))
        self.label_4.setStyleSheet("font-size: 10pt;\n"
"font-family: Verdana, serif;\n"
"color: black;\n"
"font-weight: bold;")
        self.label_4.setObjectName("label_4")
        self.cancel_btn = QtWidgets.QPushButton(CreateUser)
        self.cancel_btn.setGeometry(QtCore.QRect(200, 120, 81, 21))
        self.cancel_btn.setStyleSheet("font-family: Verdana;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"border-radius: 10px;\n"
"color: white;")
        self.cancel_btn.setObjectName("cancel_btn")

        self.retranslateUi(CreateUser)
        QtCore.QMetaObject.connectSlotsByName(CreateUser)

    def retranslateUi(self, CreateUser):
        _translate = QtCore.QCoreApplication.translate
        CreateUser.setWindowTitle(_translate("CreateUser", "Dialog"))
        self.label.setText(_translate("CreateUser", "Sign up"))
        self.label_2.setText(_translate("CreateUser", "Логин"))
        self.label_3.setText(_translate("CreateUser", "Пароль"))
        self.sign_up_button.setText(_translate("CreateUser", "Создать"))
        self.label_4.setText(_translate("CreateUser", "Подтвердите пароль"))
        self.cancel_btn.setText(_translate("CreateUser", "Отмена"))
