# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateTaskFormUFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(411, 138)
        self.name_task = QtWidgets.QLineEdit(Form)
        self.name_task.setGeometry(QtCore.QRect(10, 10, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_task.setFont(font)
        self.name_task.setText("")
        self.name_task.setObjectName("name_task")
        self.description = QtWidgets.QPlainTextEdit(Form)
        self.description.setGeometry(QtCore.QRect(10, 40, 191, 81))
        self.description.setPlainText("")
        self.description.setBackgroundVisible(False)
        self.description.setObjectName("description")
        self.create_button = QtWidgets.QPushButton(Form)
        self.create_button.setGeometry(QtCore.QRect(210, 100, 91, 24))
        self.create_button.setStyleSheet("font-family: Verdana;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"border-radius: 10px;\n"
"color: white;\n"
"")
        self.create_button.setObjectName("create_button")
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setGeometry(QtCore.QRect(310, 100, 91, 24))
        self.cancel.setStyleSheet("font-family: Verdana;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"border-radius: 10px;\n"
"color: white;\n"
"")
        self.cancel.setObjectName("cancel")
        self.audio = QtWidgets.QPushButton(Form)
        self.audio.setGeometry(QtCore.QRect(210, 10, 191, 24))
        self.audio.setStyleSheet("font-family: Verdana;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"border-radius: 10px;\n"
"color: white;\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../.designer/images/microphone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audio.setIcon(icon)
        self.audio.setObjectName("audio")
        self.photo = QtWidgets.QPushButton(Form)
        self.photo.setGeometry(QtCore.QRect(210, 40, 191, 24))
        self.photo.setStyleSheet("font-family: Verdana;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"border-radius: 10px;\n"
"color: white;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../.designer/images/png-transparent-computer-icons-user-interface-icons-angle-electronics-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.photo.setIcon(icon1)
        self.photo.setObjectName("photo")
        self.calendar_button = QtWidgets.QPushButton(Form)
        self.calendar_button.setGeometry(QtCore.QRect(210, 70, 191, 24))
        self.calendar_button.setStyleSheet("font-family: Verdana;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"border-radius: 10px;\n"
"color: white;\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../.designer/images/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calendar_button.setIcon(icon2)
        self.calendar_button.setObjectName("calendar_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_task.setPlaceholderText(_translate("Form", "Название задачи"))
        self.description.setPlaceholderText(_translate("Form", "Описание задачи"))
        self.create_button.setText(_translate("Form", "Создать"))
        self.cancel.setText(_translate("Form", "Отмена"))
        self.audio.setText(_translate("Form", "Добавить аудиозапись"))
        self.photo.setText(_translate("Form", "Добавить изображение"))
        self.calendar_button.setText(_translate("Form", "Дата выполнения задачи"))
