# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InformationFormUFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(490, 273)
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setGeometry(QtCore.QRect(10, 10, 191, 21))
        self.name_label.setStyleSheet("font-size: 8pt;\n"
"background-color: rgb(250, 250, 250);\n"
"font-family: Verdana, serif;\n"
"color: black;\n"
"font-weight: bold;")
        self.name_label.setText("")
        self.name_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_label.setObjectName("name_label")
        self.DescPlainText = QtWidgets.QPlainTextEdit(Form)
        self.DescPlainText.setGeometry(QtCore.QRect(10, 40, 191, 191))
        self.DescPlainText.setStyleSheet("font-size: 8pt;\n"
"background-color: rgb(250, 250, 250);\n"
"font-family: Verdana, serif;\n"
"color: black;\n"
"font-weight: bold;")
        self.DescPlainText.setPlainText("")
        self.DescPlainText.setObjectName("DescPlainText")
        self.date_label = QtWidgets.QLabel(Form)
        self.date_label.setGeometry(QtCore.QRect(10, 240, 191, 21))
        self.date_label.setStyleSheet("font-size: 8pt;\n"
"background-color: rgb(250, 250, 250);\n"
"font-family: Verdana, serif;\n"
"color: black;\n"
"font-weight: bold;")
        self.date_label.setText("")
        self.date_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.date_label.setObjectName("date_label")
        self.slider = QtWidgets.QSlider(Form)
        self.slider.setGeometry(QtCore.QRect(260, 240, 221, 22))
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.playBtn = QtWidgets.QPushButton(Form)
        self.playBtn.setGeometry(QtCore.QRect(210, 240, 41, 23))
        self.playBtn.setStyleSheet("font-size: 8pt;\n"
"background-color: rgb(250, 250, 250);\n"
"font-family: Verdana, serif;\n"
"color: black;\n"
"font-weight: bold;")
        self.playBtn.setText("")
        self.playBtn.setObjectName("playBtn")
        self.photo_label = QtWidgets.QLabel(Form)
        self.photo_label.setGeometry(QtCore.QRect(210, 10, 271, 221))
        self.photo_label.setStyleSheet("font-size: 8pt;\n"
"background-color: rgb(250, 250, 250);\n"
"font-family: Verdana, serif;\n"
"color: black;\n"
"font-weight: bold;")
        self.photo_label.setText("")
        self.photo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_label.setObjectName("photo_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
