# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainCalendarFormUFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate
import sqlite3


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(431, 341)
        self.main_calendarWidget = MyCalendar(Form)
        self.main_calendarWidget.setGeometry(QtCore.QRect(10, 10, 411, 281))
        self.main_calendarWidget.setObjectName("main_calendarWidget")
        self.ok_buuton = QtWidgets.QPushButton(Form)
        self.ok_buuton.setGeometry(QtCore.QRect(10, 300, 51, 31))
        self.ok_buuton.setStyleSheet("font-family: Verdana;\n"
                                     "font-weight: bold;\n"
                                     "font-size: 8pt;\n"
                                     "border-radius: 10px;\n"
                                     "color: white;")
        self.ok_buuton.setObjectName("ok_buuton")
        self.main_label_date = QtWidgets.QLabel(Form)
        self.main_label_date.setGeometry(QtCore.QRect(70, 300, 341, 31))
        self.main_label_date.setStyleSheet("font-family: Verdana;\n"
                                           "font-weight: bold;\n"
                                           "font-size: 8pt;\n"
                                           "border-radius: 10px;\n"
                                           "color:  black;")
        self.main_label_date.setText("")
        self.main_label_date.setObjectName("main_label_date")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ok_buuton.setText(_translate("Form", "ОК"))


class MyCalendar(QtWidgets.QCalendarWidget):
    def __init__(self, parent=None):
        QtWidgets.QCalendarWidget.__init__(self, parent)

    def paintCell(self, painter, rect, date):
        QtWidgets.QCalendarWidget.paintCell(self, painter, rect, date)
        con = sqlite3.connect("BD/data_base.db")
        cur = con.cursor()
        result = cur.execute("SELECT day, month, year FROM table_task_db").fetchall()
        st = set()
        for i in result:
            day, month, year = i
            st.add(QDate(year, month, day))
        for i in st:
            if date == i:
                painter.setBrush(QtGui.QColor(0, 200, 200, 50))
                painter.setPen(QtGui.QColor(0, 0, 0, 0))
                x, y, w, h = rect.x(), rect.y(), rect.width(), rect.height()
                painter.drawEllipse(x + 7, y, w - 14, h)
