# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 610)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 381, 491))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("border: 0px;\n"
"background-color: rgb(250, 250, 250);")
        self.tabWidget.setObjectName("tabWidget")
        self.all_task = QtWidgets.QWidget()
        self.all_task.setObjectName("all_task")
        self.search_btn = QtWidgets.QPushButton(self.all_task)
        self.search_btn.setGeometry(QtCore.QRect(290, 10, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.search_btn.setFont(font)
        self.search_btn.setStyleSheet("font-family: Verdana;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"border-radius: 10px;\n"
"color: white;\n"
"background-color: #7dabf6;\n"
"")
        self.search_btn.setObjectName("search_btn")
        self.search_line_edit = QtWidgets.QLineEdit(self.all_task)
        self.search_line_edit.setGeometry(QtCore.QRect(10, 10, 271, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_line_edit.setFont(font)
        self.search_line_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 10pt;")
        self.search_line_edit.setText("")
        self.search_line_edit.setObjectName("search_line_edit")
        self.taskListWidget = QtWidgets.QListWidget(self.all_task)
        self.taskListWidget.setGeometry(QtCore.QRect(10, 46, 361, 401))
        self.taskListWidget.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.taskListWidget.setObjectName("taskListWidget")
        self.important_button = QtWidgets.QPushButton(self.all_task)
        self.important_button.setGeometry(QtCore.QRect(320, 400, 51, 51))
        self.important_button.setStyleSheet("")
        self.important_button.setText("")
        self.important_button.setObjectName("important_button")
        self.tabWidget.addTab(self.all_task, "")
        self.important_task = QtWidgets.QWidget()
        self.important_task.setObjectName("important_task")
        self.search_line_edit_2 = QtWidgets.QLineEdit(self.important_task)
        self.search_line_edit_2.setGeometry(QtCore.QRect(10, 10, 271, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_line_edit_2.setFont(font)
        self.search_line_edit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 10pt;")
        self.search_line_edit_2.setText("")
        self.search_line_edit_2.setObjectName("search_line_edit_2")
        self.search_btn2 = QtWidgets.QPushButton(self.important_task)
        self.search_btn2.setGeometry(QtCore.QRect(290, 10, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.search_btn2.setFont(font)
        self.search_btn2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.search_btn2.setStyleSheet("font-family: Verdana;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"border-radius: 10px;\n"
"color: white;\n"
"background-color: #7dabf6;\n"
"")
        self.search_btn2.setObjectName("search_btn2")
        self.taskListWidget_2 = QtWidgets.QListWidget(self.important_task)
        self.taskListWidget_2.setGeometry(QtCore.QRect(10, 46, 361, 401))
        self.taskListWidget_2.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.taskListWidget_2.setObjectName("taskListWidget_2")
        self.tabWidget.addTab(self.important_task, "")
        self.calendar_btn = QtWidgets.QPushButton(self.centralwidget)
        self.calendar_btn.setGeometry(QtCore.QRect(291, 520, 101, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendar_btn.sizePolicy().hasHeightForWidth())
        self.calendar_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.calendar_btn.setFont(font)
        self.calendar_btn.setStyleSheet("font-family: Verdana;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"border-radius: 10px;\n"
"color: white;\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../.designer/images/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calendar_btn.setIcon(icon)
        self.calendar_btn.setObjectName("calendar_btn")
        self.buttons_group = QtWidgets.QButtonGroup(MainWindow)
        self.buttons_group.setObjectName("buttons_group")
        self.buttons_group.addButton(self.calendar_btn)
        self.perform_button = QtWidgets.QPushButton(self.centralwidget)
        self.perform_button.setGeometry(QtCore.QRect(13, 520, 101, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perform_button.sizePolicy().hasHeightForWidth())
        self.perform_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.perform_button.setFont(font)
        self.perform_button.setStyleSheet("font-family: Verdana;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"border-radius: 10px;\n"
"color: white;\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../.designer/images/tasks.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.perform_button.setIcon(icon1)
        self.perform_button.setObjectName("perform_button")
        self.buttons_group.addButton(self.perform_button)
        self.add_task = QtWidgets.QPushButton(self.centralwidget)
        self.add_task.setEnabled(True)
        self.add_task.setGeometry(QtCore.QRect(122, 520, 161, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_task.sizePolicy().hasHeightForWidth())
        self.add_task.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.add_task.setFont(font)
        self.add_task.setStyleSheet("font-family: Verdana;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"border-radius: 10px;\n"
"color: white;\n"
"")
        self.add_task.setObjectName("add_task")
        self.buttons_group.addButton(self.add_task)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ежедневник"))
        self.search_btn.setText(_translate("MainWindow", "Найти"))
        self.search_line_edit.setPlaceholderText(_translate("MainWindow", "найти заметку"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.all_task), _translate("MainWindow", "Все задачи"))
        self.search_line_edit_2.setPlaceholderText(_translate("MainWindow", "найти заметку"))
        self.search_btn2.setText(_translate("MainWindow", "Найти"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.important_task), _translate("MainWindow", "Важные"))
        self.calendar_btn.setText(_translate("MainWindow", "Календарь"))
        self.perform_button.setText(_translate("MainWindow", "Выполнить"))
        self.add_task.setText(_translate("MainWindow", "Добавить задачу"))
